from dotenv import load_dotenv
import os
import traceback
from langchain_core.tools import tool
from config import DefaultConfig
from langchain_core.runnables import RunnableConfig
import time
import json



@tool
def set_prompt_template(engagement_type: str) -> dict:
    """
    Based on the input engagement type, set the appropriate prompt template.
    """
    
    print(f"------------setting engagment prompt template-----------------------")
    print(f"Setting Engagement Type to: {engagement_type}.........")
    e_type=get_prompt_for_engagement_type(engagement_type)
    print(f"Setting Engagement Type to: {e_type}.........")
    return {"prompt_template": e_type}

def get_prompt_for_engagement_type(engagement_type: str) -> str:
    if engagement_type == "BUSINESS_ENVISIONING":
        return prompt_business_envisioning
    elif engagement_type == "SOLUTION_ENVISIONING":
        return prompt_solution_envisioning
    elif engagement_type == "RAPID_PROTOTYPE":
        return prompt_rapid_prototype
    elif engagement_type == "ADS":
        return prompt_ads


prompt_ads = """
    # Innovation Hub Agenda Format for Architecture & Design Session
    
    **Agenda for Innovation Hub Session**

    **Instructions**
    - Based on the input from under the **### Topics Confirmation Message ###**, consolidate content from one or more of the **Topic Types** Examples provided below, to arrive at the complete agenda list.
    - Add the above line items in the table for each Use case that needs to be implemented in the Prototype.
    - Use the durations indicated for each Topic Type, and the Start and End times need to be arrived at based on the actual Session timings.
    - Fill the placeholders for $EngagementType, $Date, $LocationName, $HubArchitectName, $CustomerName, $UseCaseDescription, $UseCaseGoals with the actual values, based on the User input. See the section **Example** below.
        $UseCaseDescription - Extract an upto ~ 15 words description of the Use Case that needs to be implemented in the Prototype, from under **### Topics Confirmation Message ###** in the input message.
        $UseCaseGoals - Infer/extract the Goals, design approach, capabilities to be implemented for the Use Case from under **### Topics Confirmation Message ###** in the input message.
    - The duration for each topic is indicated in the 'Time (IST)' Column in the Table above. This needs to be replaced with a Start and End time for each topic, with the actual time being arrived at based on when the Sessions starts and ends.
    
    
    **Topic Types**
    **Topic Type 1**: When the topic pertains to reviewing the architecture and Design of an existing Solution, and coming up with a futuristic architecture during the Engagement
    
    | Time (IST)           | Speaker                           | Topic                                                                                   | Description                                                                                                                                                                                                                                                                                                                                                                                                         |
    |----------------------|-----------------------------------|-----------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
    | ~ duration of 1 Hour | Architect Team of $Customer Name  | Review of current Architecture of $SystemName \n\n $SystemDescription                  | During this session, we will review the current architecture. The following would be discussed:\n- Overview of the Business functionalities served currently\n- Overview of the Operational Requirements served currently.\n- Technical details of the current Solution Architecture\n- Pain points in the current Architecture\n- Limitations in the current Architecture that need to be addressed in the to-be architecture\n- Any new requirements that need to be considered in the to-be architecture |
    | ~ duration of 3 Hours| $HubArchitect                     | Discuss to-be architecture of $SystemName \n\n $SystemDescription                         | During this session, we will arrive at the to-be architecture. The following would be discussed:\n- Arrive at potential Architecture & Design options for the System. Identify key Microsoft Platform Services that would be required\n- Discuss how the Business & Operational Requirements of the Solution can be met. (BCDR, HA, performance, concurrency, Security, any statutory requirements to be considered)\n- Discuss points related to Migration to the to-be architecture, as applicable\n- Technical Demo showcase of some of the key components in the to-be architecture |
                                                                                                                                | Wrap up & discuss next steps                                                                                                                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |

    
    **Topic Type 2**: When the topic pertains to reviewing the current architecture and Design of an existing Solution, and coming up with review comments, suggestions for change
    
    | Time (IST)           | Speaker                           | Topic                                                                                   | Description                                                                                                                                                                                                                                                                                                                                                                                                         |
    |----------------------|-----------------------------------|-----------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
    | ~ duration of 3 Hour | Architect Team of $Customer Name  | Review of current Architecture of $SystemName \n\n $SystemDescription                  | During this session, we will review the current architecture. The following would be discussed:\n- Overview of the Business functionalities served currently\n- Overview of the Operational Requirements served currently.\n- Technical details of the current Solution Architecture\n- Pain points in the current Architecture\n- Limitations in the current Architecture that need to be addressed in the to-be architecture\n- Any new requirements that need to be considered in the to-be architecture |
    | Hours| $HubArchitect                     | Discuss to-be architecture of $SystemName \n\n $SystemDescription                         | During this session, we will arrive at the to-be architecture. The following would be discussed:\n- Arrive at potential Architecture & Design options for the System. Identify key Microsoft Platform Services that would be required\n- Discuss how the Business & Operational Requirements of the Solution can be met. (BCDR, HA, performance, concurrency, Security, any statutory requirements to be considered)\n- Discuss points related to Migration to the to-be architecture, as applicable\n- Technical Demo showcase of some of the key components in the to-be architecture |
                   
    **Topic Type 3**: When the topic pertains to coming up with a solution architecture for a new use case during the Engagement

    | Time (IST)           | Speaker                          | Topic                                                                                      | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
    |----------------------|----------------------------------|--------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
    | ~ duration of 4 hours| Architect Team \n $Customer Name| Discuss to-be architecture options for $SystemName \n\n $SystemDescription                   | During this session, we will arrive at a draft Architecture & Design approach for the System. The following would be discussed:\n\n1) **Functional & Operational Requirements:**\n&nbsp;&nbsp;- Discuss Business requirements\n&nbsp;&nbsp;- Discuss the Operation requirements. What are the functional and operational requirements for the potential Solution? (BCDR, HA, performance, concurrency, Security, any statutory requirements to be considered, any others?)\n\n2) **Data Sources:**\n&nbsp;&nbsp;- The different Data sources to be considered and how they can be accessed\n\n3) **Architecture & Design Choices:**\n&nbsp;&nbsp;- The choices available to power this use case on the Microsoft Platform\n\n4) **Technology Showcase:**\n&nbsp;&nbsp;- Demonstrations of key components in the Architecture\n\n6) **Whiteboard Session:**\n&nbsp;&nbsp;- Whiteboard the potential Architecture & Design approaches


    **Topic Type 4**: When the topic pertains to devling deep into a technology area, showcasing the technology capabilities and features

    | Time (IST)          | Speaker     | Topic                                                                                     | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
    |---------------------|-------------|-------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
    | Duration ~ 1 hour   | $HubArchitect | Technology Showcase \n\n **Topic:** $TopicName                                      | During this Technology Showcase session, $HubArchitect will lead an in-depth exploration of **$TopicName**. The session will cover essential technology services, tools, and frameworks such as Azure, AWS, and modern development environments. Through live demonstrations and practical examples, attendees will gain insights into integration strategies, performance optimization, and security best practices. This interactive session is designed to empower participants to implement innovative solutions that address real-world challenges and drive business transformation. |


    **Topic Type 5**: When the topic pertains to discussing popular patterns, best practices and reference architectures

    | Time (IST)         | Speaker      | Topic                                                                                           | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
    |--------------------|--------------|-------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
    | Duration ~ 1 hour  | $HubArchitect | Reference Architectures & Best Practices \n\n **Topic:** $TopicName                         | In this session, $HubArchitect will present a comprehensive review of reference architectures, industry patterns, and best practices that drive robust solution design. The discussion will cover key technology services such as Azure and AWS, along with frameworks like Kubernetes and modern DevOps tools, ensuring that all aspects of scalability, security, and performance are addressed. Attendees will gain practical insights into how these architectures and patterns can be leveraged to build resilient systems that meet both current and future business demands. |


    
    **Example**
    Engagement Type: ADS
    Customer Name: Dr. Reddy's Lab (DRL)
    Date: 26-Nov-2024
    Location: Microsoft Innovation Hub, Bengaluru
    
    | Time (IST)             | Speaker                           | Topic                                                                                                                                                        | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
    |------------------------|-----------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
    | 10:00 AM-10:15 AM      | Moderator                         | Welcome & Introductions                                                                                                                                      | The Firstsource Architect Team would share their top of mind and key take aways expected from the Session                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
    | 10:15 AM-11:15 AM      | Architect Team of $Customer Name  | Review of current Architecture of $SystemName \n\n $SystemDescription                                                                                     | During this session, we will review the current architecture. The following would be discussed:\n- Overview of the Business functionalities served currently\n- Overview of the Operational Requirements served currently\n- Technical details of the current Solution Architecture\n- Pain points in the current Architecture\n- Limitations in the current Architecture that need to be addressed in the to-be architecture\n- Any new requirements that need to be considered in the to-be architecture |
    | 11:15 AM -1:30 PM      | $HubArchitect                     | Discuss to-be architecture of $SystemName \n\n $SystemDescription                                                                                            | During this session, we will arrive at the to-be architecture. The following would be discussed:\n- Arrive at potential Architecture & Design options for the System. Identify key Microsoft Platform Services that would be required\n- Discuss how the Business & Operational Requirements of the Solution can be met (BCDR, HA, performance, concurrency, Security, any statutory requirements to be considered)\n- Discuss points related to Migration to the to-be architecture, as applicable\n- Technical Demo showcase of some of the key components in the to-be architecture |
    | 1:30 PM – 2:30 PM      |                                   | Lunch                                                                                                                                                        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
    | 2:30 PM -3:30 PM       | $HubArchitect                     | [CONTINUED] Discuss to-be architecture of $SystemName \n\n $SystemDescription                                                                                  | During this session, we will arrive at the to-be architecture. The following would be discussed:\n- Arrive at potential Architecture & Design options for the System. Identify key Microsoft Platform Services that would be required\n- Discuss how the Business & Operational Requirements of the Solution can be met (BCDR, HA, performance, concurrency, Security, any statutory requirements to be considered)\n- Discuss points related to Migration to the to-be architecture, as applicable\n- Technical Demo showcase of some of the key components in the to-be architecture |
    | 3:30 PM -4:30 PM       | $HubArchitect                     | Technology Showcase \n\n **Topic:** $TopicName                                                                                                             | During this Technology Showcase session, $HubArchitect will lead an in-depth exploration of **$TopicName**. The session will cover essential technology services, tools, and frameworks such as Azure, AWS, and modern development environments. Through live demonstrations and practical examples, attendees will gain insights into integration strategies, performance optimization, and security best practices. This interactive session is designed to empower participants to implement innovative solutions that address real-world challenges and drive business transformation. |
    | 4:30 PM -5:15 PM       | $HubArchitect                     | Reference Architectures & Best Practices \n\n **Topic:** $TopicName                                                                                        | In this session, $HubArchitect will present a comprehensive review of reference architectures, industry patterns, and best practices that drive robust solution design. The discussion will cover key technology services such as Azure and AWS, along with frameworks like Kubernetes and modern DevOps tools, ensuring that all aspects of scalability, security, and performance are addressed. Attendees will gain practical insights into how these architectures and patterns can be leveraged to build resilient systems that meet both current and future business demands. |
    | 5:15 PM-5:30 PM        |                                   | Wrap up & discuss next steps                                                                                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |

    """

prompt_rapid_prototype = """
    # Innovation Hub Agenda Format for Rapid Prototype
    
    **Agenda for Innovation Hub Session**
    Engagement Type: $EngagementType
    Customer Name: $CustomerName
    Date: $Date (format - DD-MMM-YYYY)
    Location: $locationName
    
    | Time (IST)      | Speaker                                                                                                            | Topic                                                  | Description                                                                                                                                                                                                                                                                                                                                                                      |
    |-----------------|--------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
    | ~ 60 minutes    | Development Team from $CustomerName \n\n Technical Architects from Microsoft:\n- $HubArchitectName          | Understanding the Requirements & Goals behind Use Case \n\n **Use Case:** $UseCaseDescription  | Before we get into building the Prototype, we will discuss the following:\n- The functional and operational requirements of the use case that should be realized\n- Identify the Solution Architecture design options. If an Architecture has already been determined, for the use case from an ADS Session earlier, review and conclude on its use for the Prototype.\n- Ensure all the requisite Cloud Services are provisioned, all necessary software installed and licenses available, and the Development team has access to them.\n\n \n----- Goals, design approach, capabilities to be implemented -----\n\n- $UseCaseGoals |
    | ~ 4 hours       | Development Team from DRL (Dr. Reddy’s Lab) \n\n Technical Architects from Microsoft:\n- $HubArchitectName   | Build the Prototype \n\n **Use Case:** $UseCaseDescription | Development, deployment testing and validating the Use case implementation                                                                                                                                                                                                                                                                                                      |


    **Instructions**
    - Add the above line items in the table for each Use case that needs to be implemented in the Prototype.
    - The durations indicated above have to be maintained, and the Start and End times arrived at based on the actual Session timings.
    - Fill the placeholders for $EngagementType, $Date, $LocationName, $HubArchitectName, $CustomerName, $UseCaseDescription, $UseCaseGoals with the actual values, based on the User input. See the section **Example** below.
        $UseCaseDescription - Extract an upto ~ 15 words description of the Use Case that needs to be implemented in the Prototype, from under **### Topics Confirmation Message ###** in the input message.
        $UseCaseGoals - Infer/extract the Goals, design approach, capabilities to be implemented for the Use Case from under **### Topics Confirmation Message ###** in the input message.
    - The duration for each topic is indicated in the 'Time (IST)' Column in the Table above. This needs to be replaced with a Start and End time for each topic, with the actual time being arrived at based on when the Sessions starts and ends.
    
    
    **Example**
    Engagement Type: Rapid Prototype
    Customer Name: Dr. Reddy's Lab (DRL)
    Date: 26-Nov-2024
    Location: Microsoft Innovation Hub, Bengaluru
    
    | Time (IST)           | Speaker                                                                                                                                             | Topic                                                                                                                                              | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
    |----------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
    | 10:00 AM-10:15 AM    | Moderator                                                                                                                                           | Welcome & Introductions                                                                                                                            | The DRL Team would share their top of mind and key take aways expected from the Session                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
    | 10:15 AM – 11:15 AM  | Development Team from DRL (Dr. Reddy’s Lab)\n\nand Technical Architects from Microsoft:\n- Srikantan Sankaran                                        | Understanding the Requirements & Goals behind Use Case\n\nUse Case 1: Reasoning over Contract Documents and let users QnA over them          | Before we get into building the Prototype, we will discuss the following:\n- The functional and operational requirements of the use case that should be realized\n- Identify the Solution Architecture design options. If an Architecture has already been determined, for the use case from an ADS Session earlier, review and conclude on its use for the Prototype.\n- Ensure all the requisite Cloud Services are provisioned, all necessary software installed and licenses available, and the Development team has access to them.\n\n----- Goals, design approach, capabilities to be implemented -----\n- Consider a code first approach to build the Solution using Azure AI Studio. Use Azure OpenAI Model from the Model Catalog. Use Azure AI Search for RAG over document manuals |
    | 11:15 AM – 1:30 PM   | Development Team from DRL (Dr. Reddy’s Lab)\n\nand Technical Architects from Microsoft:\n- Srikantan Sankaran                                        | Build the Prototype\n\nUse Case 1: Reasoning over Contract Documents and let users QnA over them                                               | Development, deployment testing and validating the Use case implementation                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
    | 1:30 PM – 2:30 PM    |                                                                                                                                                     | Lunch                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
    | 2:30 PM – 4:15 PM    | Development Team from DRL (Dr. Reddy’s Lab)\n\nand Technical Architects from Microsoft:\n- Srikantan Sankaran                          | Build the Prototype - continued\n\nUse Case 1: Reasoning over Contract Documents and let users QnA over them                                   | Development, deployment testing and validating the Use case implementation                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
    | 10:15 AM-11:15 AM    | Development Team from DRL (Dr. Reddy’s Lab)\n\nand Technical Architects from Microsoft:\n- Bishnu Agrawal                                               | Understanding the Requirements & Goals behind Use Case\n\nUse Case 2: Conversational BI over structured data                                      | Before we get into building the Prototype, we will discuss the following:\n- The functional and operational requirements of the use case that should be realized\n- Identify the Solution Architecture design options. If an Architecture has already been determined, for the use case from an ADS Session earlier, review and conclude on its use for the Prototype.\n- Ensure all the requisite Services in Azure are provisioned, all necessary software installed and available, and the Development team has access to them.\n\n----- Goals, design approach, capabilities to be implemented -----\n- Consider a code first approach to build the Solution using Microsoft Fabric, AI Skills in Microsoft Fabric, and supplement with Power BI Copilot for generating reports based on Natural language user input |
    | 11:15 AM – 1:30 PM   | Development Team from DRL (Dr. Reddy’s Lab)\n\nand Technical Architects from Microsoft:\n- Bishnu Agrawal                          | Build the Prototype\n\nUse Case 2: Conversational BI over structured data                                                                       | Development, deployment testing and validating the Use case implementation                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
    | 2:30 PM – 4:15 PM    | Development Team from DRL (Dr. Reddy’s Lab)\n\nand Technical Architects from Microsoft:\n- Bishnu Agrawal                          | Build the Prototype - continued\n\nUse Case 2: Conversational BI over structured data                                                           | Development, deployment testing and validating the Use case implementation                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
    | 4:15 PM-5:00 PM      |                                                                                                                                                     | Wrap up & discuss next steps                                                                                                                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |

    """

prompt_business_envisioning = """
    # Innovation Hub Agenda Format for Business Envisioning
    
    **Agenda for Innovation Hub Session**
    Engagement Type: $EngagementType
    Customer Name: $CustomerName
    Date: $Date (format - DD-MMM-YYYY)
    Location: $locationName
    
    | Time (IST)                  | Speaker                | Topic                                                  | Description                                             |
    |-----------------------------|------------------------|--------------------------------------------------------|---------------------------------------------------------|
    | <$StartTime> - <$EndTime>   |  $SpeakerName          | <$TopicTitle>                                          | $TopicDescription |
    | <$StartTime> - <$EndTime>   | $SpeakerName           | <$TopicTitle>                                          | $TopicDescription |
    ... and so on for the other topics ...

    **Instructions**
    Your task is to generate the Agenda Topics for the Innovation Hub Session based on the User input, under **### Topics Confirmation Message ###**.
    - Fill the placeholders for $EngagementType, $Date, $LocationName, $SpeakerName, $CustomerName, $TopicTitle, $TopicDescription with the actual values, based on the User input. See the section **Example** below.
        $TopicTitle - Extract an upto ~ 10 words description of the topic, from under **### Topics Confirmation Message ###** in the input message.
        $TopicDescription - Generate a compelling description, from ~50 words to ~100 words,for this topic that captures the expectations on what needs to be delivered during the session. Use the content from under **### Topics Confirmation Message ###** in the input message to generate the description. Properly format this description in Markdown.
        
    
    - When doing so, follow the Business Rules below:
    
        ## Business Rules

        ### Rule 1: Engagement Type, Technical Depth and duration of the Topics 
        - Topics & the Topic Descriptions generated must be non-technical, driven by business /domain specific use case scenarios.
        - No single topic should span more than 1 1/2 hours.
        - An ideal topic duration is 1 hour.
        - A topic duration of 30 minutes is acceptable.
        ### Rule 2: Session Line Items Creation
        - #### Mandatory Line Items to be added to the Agenda Table
            - The **first topic** must always be **Welcome & Introductions**.
            - The **last topic** must always be **Wrapup & discuss next steps**.
        ### Rule 3: Speaker Assignment
            - $SpeakerName - Assign a Speaker Name to each topic in the Agenda Table based on the **SpeakerMappingTable** section below, after determining which item in the table the topic semantically matches and then retrieve the Speaker Name from the table.
            - If the Lead Architect for this Engagement, under the **### Topics Confirmation Message ###**, is a designated Speaker on a topic that is listed in the **SpeakerMappingTable**, then assign the Lead Architect as the Speaker for that topic.
            - If no Speaker can be identified for the topic, ask the user to suggest a Speaker Name. If the user cannot provide it, mark it as TBD
        ### Rule 4: Topic Sequencing
            - The **first topic** must always be **Welcome & Introductions**.
            - Topics that involve the Leadership Team of the Customer must be scheduled right after the Introductions.
            - Keynote topics, Latest trends topics, etc must be scheduled right after the Leadership Team of the Customer.
            - Include all topics from **### Topics Confirmation Message ###** in the Agenda Table, based on the sequencing rule.
            - The **last topic** must always be **Wrapup & discuss next steps**.
        ### Rule 5: Session Timings
            1. By default, the Innovation Hub Session starts at 10 AM, unless the provided context indicates another start time (e.g., 2 PM if the customer prefers a later start).
            2. Insert a 15-minute break every 2 hours in the Agenda.
            3. The lunch break should be 1 hour long and start any time between 1:00 PM and 2:00 PM, depending on the schedule of the preceding topics.
            4. The last topic in the Agenda must conclude by 5:00 PM, but as an exception, the end time can go upto 6:00 PM. Confirm with the user if an end time beyond 5 PM is acceptable.
            5. If topics exceed the available time until 6:00 PM, add the remaining topics to the next working day. Confirm with the user if this is acceptable.

    
    **SpeakerMappingTable**
    ```markdown
    | Topics                                                                                                                        | Speaker Name                                                        |
    |-------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------|
    | AI Keynote Session, AI technology Trends, Art of the Possible                                                                 | **Sandeep Alur**\nCTO Microsoft Innovation Hub India              |
    | Azure AI Services, Agentic Frameworks in Azure, Azure AI Foundry, Azure AI Studio, Azure Machine Learning, Azure AI Models, Azure Model Catalogs, Custom copilots            | **Srikantan Sankaran**\nSr. Technical Architect, Microsoft Innovation Hub |
    | Modern Work, Microsoft 365, Microsoft 365 Copilot, Security Copilot, Microsoft 365 Copilot Agents, Microsoft Pages (Loop), Office Productivity | **Pallavi Lokesh**\nSr. Technical Architect, Microsoft Innovation Hub |
    | Azure AI, Apps & Infrastructure, App Modernization, Workload / App Containerization, GitHub, GitHub Copilot, GitHub Advanced Security (GHAS) | **Divya SK**\nSr. Technical Architect, Microsoft Innovation Hub    |
    | Azure Data Workloads, Microsoft Fabric, Power BI, Data & Analytics, Data Platform, Databricks, Analytics & Reporting, Real time Intelligence, Data FActory, Data Wrangling | **Bishnu Agrawal**\nTechnical Architect, Microsoft Innovation Hub  |
    | Low code No code platform, Business Productivity, Dynamics 365 CRM / ERP, Copilot Studio, Power Automate, AI Builder, Business Apps , Power Apps, Power Pages, Dataverse, Virtual Reality , Augmented Reality | **Vishakha Arbat**\nTechnical Architect, Microsoft Innovation Hub  |
    | Microsoft Point of view of the Retail Industry Domain and how AI has helped in digital transformation                      | **Srinivasa Sivakumar**\nSenior Industry Advisor for Retail, Microsoft  |
    | Microsoft Point of view of the Manufacturing & Supply Chain Industry Domain and how AI has helped in digital transformation                      | **Arvind Vedavit**\nSenior Industry Advisor for Manufacturing and Supply Chain, Microsoft  |
    
    **Example**
    
    **Agenda for Innovation Hub Session**
    Engagement Type: Business Envisioning
    Customer Name: Myntra
    Date: 20-Jan-2025
    Location: Microsoft Innovation Hub, Bengaluru
    
    | Time (IST)          | Speaker                                               | Topic                                              | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
    |---------------------|-------------------------------------------------------|----------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
    | 10:00 AM - 10:15 AM | Moderator                                             | Kick-off                                           | Introductions and Welcome from Microsoft Leadership                                                                                                                                                                                                                                                                                                                                                                                                             |
    | 10:15 AM - 11:15 AM | Leadership Team of Myntra & Flipkart                  | Understand Myntra’s AI Vision                      | - Myntra Leadership team to share their business priorities and how they think AI could help meet their priorities.\n- Flipkart Team could provide a view on all that they have done so far with Generative AI and what outcomes were driven.                                                                                                                                                                                                                  |
    | 11:15 AM - 12:30 PM | Sandeep Alur\nDirector, Microsoft Innovation Hub    | Generative AI and LLMs: The Art of the Possible      | We have entered the era of conversations powered by the LLMs and SLMs. The last few months have witnessed an exponential elevation to the reasoning power of GPT series, which now supports multimodal conversations. During this session, you will:\n1. Get a peek into the latest in the world of Language Models\n2. Witness key industry use cases that are making headlines.\n3. See a lineup of dominant use cases specific to Retail & Fashion |
    | 12:30 PM - 1:15 PM  | Pallavi Lokesh\nSr. Technical Architect               | Personal Productivity powered by Microsoft’s Copilots | You will witness the power of AI Powered Copilots that elevate workplace productivity. We will demonstrate how Copilots in our product portfolio (M365, Teams, Outlook, Word, PowerPoint, Excel,) help you and your organization work more efficiently.                                                                                                                                                                                                       |
    | 1:15 PM - 2:15 PM   | Lunch                                                 |                                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
    | 2:15 PM - 2:30 PM   | Myntra and Microsoft Team                              | Wrap up and Next Steps                             |                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |

"""


prompt_solution_envisioning = """
    # Innovation Hub Agenda Format for Business Envisioning
    
    **Agenda for Innovation Hub Session**
    Engagement Type: $EngagementType
    Customer Name: $CustomerName
    Date: $Date (format - DD-MMM-YYYY)
    Location: $locationName
    
    | Time (IST)                  | Speaker                | Topic                                                  | Description                                             |
    |-----------------------------|------------------------|--------------------------------------------------------|---------------------------------------------------------|
    | <$StartTime> - <$EndTime>   | $SpeakerName          | <$TopicTitle>                                          | $TopicDescription |
    | <$StartTime> - <$EndTime>   | $SpeakerName           | <$TopicTitle>                                          | $TopicDescription |
    ... and so on for the other topics ...

    **Instructions**
    Your task is to generate the Agenda Topics for the Innovation Hub Session based on the User input, under **### Topics Confirmation Message ###**.
    - Fill the placeholders for $EngagementType, $Date, $LocationName, $SpeakerName, $CustomerName, $TopicTitle, $TopicDescription with the actual values, based on the User input. See the section **Example** below.
        $TopicTitle - Extract an upto ~ 10 words description of the topic, from under **### Topics Confirmation Message ###** in the input message.
        $TopicDescription - Generate a compelling description, from ~50 words to ~100 words,for this topic that captures the expectations on what needs to be delivered during the session. Use the content from under **### Topics Confirmation Message ###** in the input message to generate the description. Properly format this description in Markdown. When its a technical topic, make sure you include the names of the technology services, tools, frameworks, etc. that will be discussed.
        
    
    - When doing so, follow the Business Rules below:
    
        ## Business Rules

        ### Rule 1: Engagement Type, Technical Depth and duration of the Topics 
        - Topics & the Topic Descriptions generated can be either technical or non-technical in nature.
        -   Use the information under **### Topics Confirmation Message ###**, to arrive at the details of the topic and topic description, and determine the nature of the discussion.
        - No single topic should span more than 1 1/2 hours.
        - An ideal topic duration is 1 hour.
        - A topic duration of 30 minutes is acceptable.
        ### Rule 2: Session Line Items Creation
        - #### Mandatory Line Items to be added to the Agenda Table
            - The **first topic** must always be **Welcome & Introductions**.
            - The **last topic** must always be **Wrapup & discuss next steps**.
        ### Rule 3: Speaker Assignment
            - $SpeakerName - Assign a Speaker Name to each topic in the Agenda Table based on the **SpeakerMappingTable** section below, after determining which item in the table the topic semantically matches and then retrieve the Speaker Name from the table.
            - If the Lead Architect for this Engagement, under the **### Topics Confirmation Message ###**, is a designated Speaker on a topic that is listed in the **SpeakerMappingTable**, then assign the Lead Architect as the Speaker for that topic.
            - If no Speaker can be identified for the topic, ask the user to suggest a Speaker Name. If the user cannot provide it, mark it as TBD
        ### Rule 4: Topic Sequencing
            - The **first topic** must always be **Welcome & Introductions**.
            - Topics that involve the Leadership Team of the Customer must be scheduled right after the Introductions.
            - Keynote topics, Latest trends topics, etc must be scheduled right after the Leadership Team Session from the Customer, if there is one.
            - Include all topics from **### Topics Confirmation Message ###** in the Agenda Table, based on the sequencing rule.
            - When splitting a session to accommodate Break, Lunch Break, etc ensure that you resume with the same speaker and topic after the break.
            - The **last topic** must always be **Wrapup & discuss next steps**.
        ### Rule 5: Session Timings
            1. By default, the Innovation Hub Session starts at 10 AM, unless the provided context indicates another start time (e.g., 2 PM if the customer prefers a later start).
            2. Insert a 15-minute break every 2 hours in the Agenda.
            3. The lunch break should be 1 hour long and start any time between 1:00 PM and 2:00 PM, depending on the schedule of the preceding topics.
            4. The last topic in the Agenda must conclude by 5:00 PM, but as an exception, the end time can go upto 6:00 PM. Confirm with the user if an end time beyond 5 PM is acceptable.
            5. If topics exceed the available time until 6:00 PM, add the remaining topics to the next working day. Confirm with the user if this is acceptable.

    
    **SpeakerMappingTable**
    ```markdown
    | Topics                                                                                                                        | Speaker Name                                                        |
    |-------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------|
    | AI Keynote Session, AI technology Trends, Art of the Possible                                                                 | **Sandeep Alur**\nCTO Microsoft Innovation Hub India              |
    | Azure AI Services, Agentic Frameworks in Azure, Azure AI Foundry, Azure AI Studio, Azure Machine Learning, Azure AI Models, Azure Model Catalogs, Custom copilots            | **Srikantan Sankaran**\nSr. Technical Architect, Microsoft Innovation Hub |
    | Modern Work, Microsoft 365, Microsoft 365 Copilot, Security Copilot, Microsoft 365 Copilot Agents, Microsoft Pages (Loop), Office Productivity | **Pallavi Lokesh**\nSr. Technical Architect, Microsoft Innovation Hub |
    | Azure AI, Apps & Infrastructure, App Modernization, Workload / App Containerization, GitHub, GitHub Copilot, GitHub Advanced Security (GHAS) | **Divya SK**\nSr. Technical Architect, Microsoft Innovation Hub    |
    | Azure Data Workloads, Microsoft Fabric, Power BI, Data & Analytics, Data Platform, Databricks, Analytics & Reporting, Real time Intelligence, Data FActory, Data Wrangling | **Bishnu Agrawal**\nTechnical Architect, Microsoft Innovation Hub  |
    | Low code No code platform, Business Productivity, Dynamics 365 CRM / ERP, Copilot Studio, Power Automate, AI Builder, Business Apps , Power Apps, Power Pages, Dataverse, Virtual Reality , Augmented Reality | **Vishakha Arbat**\nTechnical Architect, Microsoft Innovation Hub  |
    | Microsoft Point of view of the Retail Industry Domain and how AI has helped in digital transformation                      | **Srinivasa Sivakumar**\nSenior Industry Advisor for Retail, Microsoft  |

    
    **Example**
    
    **Agenda for Innovation Hub Session**
    Engagement Type: Solution Envisioning
    Customer Name: Pharmeasy
    Date: 01-Oct-2024
    Location: Microsoft Innovation Hub, Bengaluru
    
    | Time (IST)          | Speaker                                  | Topic                                                                                                                                   | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
    |---------------------|------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
    | 2:00 PM – 2:15 PM   | Moderator                                | Welcome & Introductions                                                                                                                 | Welcome $CustomerName attendees. Introduction to the Microsoft team.                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
    | 2:15 PM – 2:45 PM   | Srikantan Sankaran\nSr. Architect      | Solution Envisioning for Customer Support scenarios to help with:\n- Reduced load on Customer Support Agents (humans)\n- Improved Customer experience | Use Intelligent Bot to help customers self-serve on queries related to their orders, refunds, etc., by integrating with a variety of back-end systems (APIs, databases, manual/document archives).\n- Discuss design options with Azure AI Studio Prompt flow, code-first with Microsoft Bot Framework.\n- Discuss approaches with Open AI Function Calling for intent and entity detection, routing of user input to relevant downstream integrations.\n- Use orchestration agents to perform RAG on various systems.\n- Discover key operational requirements that could determine the choice of LLMs/SLMs, vector databases, etc. |
    | 2:45 PM – 3:15 PM   | Arvind Raman\nSr. Technical Specialist | Solution Envisioning for use cases related to Health QnA for Customers:\n1. Help users with first level QnA\n2. Ability to discuss taboo subjects like dermatology, paediatric, diabetes, etc. | Discuss how Azure Health Bot can be used as a first level assistant for customers:\n- Access to credible medical information\n- Integration with Generative AI capabilities for natural language conversations\n- Ability to connect to Pharmeasy’s back-end systems\n- Compliance with HIPAA\nDiscover key operational requirements at Pharmeasy and discuss how these could be met in the solution.                                                                                                                                     |
    | 3:15 PM – 3:45 PM   | Srikantan Sankaran\nSr. Architect      | Solution Envisioning for Customer Order Confirmation Flow:\n- Reduce turnaround time to validate an uploaded prescription from 5 minutes to ~1 minute\n- Digitize prescriptions and perform image-based search and verification\n- Discuss how QC on medicine consignments can be done prior to inventory intake\n- Tally medicine count on invoice with details (batch number, quantity, medicine name, price, etc.) | Discuss how:\n• Azure Document Intelligence Service and new Custom Generative Models can digitize documents based on templates and layouts\n  - Identify key information like headers, doctor’s credentials, registration numbers, and medicine details with clarity on dosage\n  - Support for printed/handwritten prescription details\n• Provide confirmation back in the app with a Go/No-Go decision based on the veracity of the scanned information.\nDiscover key operational requirements at Pharmeasy and discuss how these could be met in the solution. |
    | 3:45 PM – 4:00 PM   | Break                                    |                                                                                                                                        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
    | 4:00 PM – 4:30 PM   | Srikantan Sankaran\nSr. Architect      | Solution Envisioning for Drug Discovery by Customers:\n- For customer base in Tier 2-3 cities\n- Search for medicines rather than browsing a catalog of ~3 lakh products\n- Image-based search of tablet strips (blisters?)           | Solution Envisioning for such use cases using Azure AI Search:\n- Perform image-based search\n- Search for specific drugs (ayurvedic) or combination drugs\nDiscover key operational requirements at Pharmeasy and discuss how these could be met in the solution.                                                                                                                                                                                                                                                     |
    | 4:30 PM – 5:00 PM   | Srikantan Sankaran\nSr. Architect      | Solution Envisioning for Conversational Commerce:\n- Use of voice to interact with the AI assistant\n- Access through channels like WhatsApp, custom app                             | Solution Envisioning for such use cases using Azure Speech and Language Services:\n- STT and TTS capabilities\n- Support for different Indian languages\nDiscover key operational requirements at Pharmeasy and discuss how these could be met in the solution.                                                                                                                                                                                                                                                       |
    | 5:00 PM – 5:15 PM   | Pharmeasy and Microsoft Team             | Wrap up and Next Steps                                                                                                                  |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |

"""